<?php

/**
 * @file
 * A 3D Object Model using Field Types API.
 */
use Drupal\Core\Routing\CurrentRouteMatch;
/**
 * Implements hook_help().
 */
function threedom_coordinates_help($route_name, CurrentRouteMatch $route_match) {
  switch ($route_name) {
    case 'help.page.threedom_coordinates':
      $txt = file_get_contents(drupal_get_path('module', 'threedom_coordinates') . '/README.md');
      return str_replace("\n", "\n<br />", SafeMarkup::checkPlain($txt));
  }
  return '';
}